[plugin]
repository = "https://github.com/gnargle/NICEDamage.git"
commit = "f8cac911c78e568c8a4a551775812245f93bebeb"
owners = ["gnargle"]
project_path = "NICEDamage"
changelog = "Update NICEDamage for 7.2"
