[plugin]
repository = "https://github.com/gnargle/NICEDamage.git"
commit = "b472069c5a461c8e15e63a19d3fa616ee8bac89f"
owners = ["gnargle"]
project_path = "NICEDamage"
changelog = "Update NICEDamage for 7.2"
