[plugin]
repository = "https://github.com/gnargle/LPHotbars.git"
commit = "98e6fbc3ecbce3278409118fe922ab8d7c30ab32"
owners = ["gnargle"]
project_path = "LaunchpadHotbars"
changelog = "Initial release"